services:
  # PHP-FPM
  phpfpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${APP_NAME:-app}-phpfpm
    working_dir: /var/www/html/backend
    volumes:
      - ./backend:/var/www/html/backend
    environment:
      APP_ENV: ${APP_ENV:-local}
      DATABASE_URL: mysql://${DB_USERNAME:-root}:${DB_PASSWORD:-password}@mariadb:3306/${DB_DATABASE:-database}
    ports:
      - "9000:9000"
    command: php-fpm
    depends_on:
      - mariadb
      - redis
    networks:
      - net

  # MariaDB
  mariadb:
    image: mariadb:latest
    container_name: ${APP_NAME:-app}-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_DATABASE:-database}
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - net

  # Redis
  redis:
    image: redis:latest
    container_name: ${APP_NAME:-app}-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - net

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_NAME:-app}-phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${DB_USERNAME:-root}
      PMA_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - net

  # Node.js
  node:
    image: node:latest
    container_name: ${APP_NAME:-app}-node
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev # USE WHEN PROJECT IS CREATED
    networks:
      - net

  # Nginx
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME:-app}-nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html/backend
      - ./frontend:/var/www/html/frontend
    ports:
      - "80:80"
    depends_on:
      - phpfpm
      - node
    networks:
      - net

volumes:
  mariadb-data:
  redis-data:

networks:
  net:
    driver: bridge